export const FETCH_ALL_ZONE_PENDING = 'FETCH_ALL_ZONE_PENDING';
export const FETCH_ALL_ZONE_SUCCESS = 'FETCH_ALL_ZONE_SUCCESS';
export const FETCH_ALL_ZONE_FAILURE = 'FETCH_ALL_ZONE_FAILURE';

export const SET_ZONE_PENDING = 'SET_ZONE_PENDING';
export const SET_ZONE_SUCCESS = 'SET_ZONE_SUCCESS';
export const SET_ZONE_FAILURE = 'SET_ZONE_FAILURE';

export const SET_ALARM_PENDING = 'SET_ALARM_PENDING';
export const SET_ALARM_FAILURE = 'SET_ALARM_FAILURE';

