export const FETCH_ALL_ZONE_PENDING = 'FETCH_ALL_ZONE_PENDING';
export const FETCH_ALL_ZONE_SUCCESS = 'FETCH_ALL_ZONE_SUCCESS';
export const FETCH_ALL_ZONE_FAILURE = 'FETCH_ALL_ZONE_FAILURE';

export const SET_ZONE_PENDING = 'SET_ZONE_PENDING';
export const SET_ZONE_SUCCESS = 'SET_ZONE_SUCCESS';
export const SET_ZONE_FAILURE = 'SET_ZONE_FAILURE';

export const SET_ALARM_PENDING = 'SET_ALARM_PENDING';
export const SET_ALARM_FAILURE = 'SET_ALARM_FAILURE';

export const RECEIVE_DHT22_DATA = 'RECEIVE_DHT22_DATA';

export const FETCH_TEMPERATURE_PENDING = 'FETCH_TEMPERATURE_PENDING';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
